### ISSUE TITLE
Google drive link does not work

### ISSUE THREAD

**Issue by hnekoeiq** [pierrecham/TTK4900#1]
Hi @pierrecham,

Thanks for the great repo. Could you fix the link to google drive?

**Comment by pierrecham** [comment]
Hi, the folder that the link was reffering to was permanently deleted during cleanup. I tried to contact Google to recover it, but without luck. Sorry for the inconvenience, I will remove the link from the repo.

**Comment by pierrecham** [comment]
Hi, I have recovered the folder and updated the link to it.
